### ISSUE TITLE
Make it clear that the eccode artefact is derived from expasy and not enzyme-database org

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/pyobo#186]
expasy lags behind enzyme-database.org. The latter is the true SoT for EC. However, using expasy is better because it is synced with uniprot.

See for example

- https://www.enzyme-database.org/query.php?ec=3.6.4.12 obsoleted
- https://enzyme.expasy.org/EC/3.6.4.12 no record of obsoletion

So keep code as is but make provenance clear. This is current header:

```yaml
property_value: http://purl.org/dc/elements/1.1/title "Enzyme Commission Code" xsd:string
property_value: http://purl.org/dc/terms/license "CC-BY-4.0" xsd:string
property_value: http://purl.org/dc/elements/1.1/description "The Enzyme Classification contains the recommendations of the Nomenclature Committee of the International Union of Biochemistry and Molecular Biology on the nomenclature and classification of enzyme-catalysed reactions." xsd:string
```

See also:

- https://github.com/geneontology/go-ontology/issues/27997
