### ISSUE TITLE
include EC mappings in rhea release

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/pyobo#358]
pyobo is missing all EC mappings from RHEA

https://www.rhea-db.org/rhea/11872

<img width="921" alt="Image" src="https://github.com/user-attachments/assets/caba767b-d9f6-49e9-ac63-8ee89264af44" />

this doesn't align with the pyobo translation:

```yaml
predicate_id: oio:hasDbXref
mapping_justification: semapv:UnspecifiedMatching
subject_id: RHEA:11873
subject_label: corticosterone + 2 reduced [adrenodoxin] + O2 + 2 H(+) => 18-hydroxycorticosterone
  + 2 oxidized [adrenodoxin] + H2O
object_id: https://metacyc.org/compound?orgid=META&id=RXN66-360
subject_source: RHEA
object_source: metacyc

---
predicate_id: oio:hasDbXref
mapping_justification: semapv:UnspecifiedMatching
subject_id: RHEA:11875
subject_label: corticosterone + 2 reduced [adrenodoxin] + O2 + 2 H(+) <=> 18-hydroxycorticosterone
  + 2 oxidized [adrenodoxin] + H2O
object_id: http://www.kegg.jp/entry/R03262
subject_source: RHEA
object_source: kegg
```
